sourceFolder: source
sourceTypes:
  - md
  - txt
  - html
templatesFolder: templates
assetsFolder: public
publicFolder: public
photosFolder: photos

lang: en
url: http://morning.photos
postsPerPage: 10
postsInFeed: 15
cutTag: <!--more-->

artist: Artem Sapegin

partners:
  'amazon.com': '?tag=artesapesphot-20'
  'ozon.ru': '?partner=sapegin'
