sourceFolder: source
sourceTypes:
  - md
  - txt
  - html
templatesFolder: templates
assetsFolder: public
publicFolder: public
photosFolder: photos

lang: en
url: http://morning.photos
postsPerPage: 10
postsInFeed: 15
cutTag: <!--more-->

artist: Artem Sapegin

partners:
  'amazon.com': '?tag=artesapesphot-20'
  'ozon.ru': '?partner=sapegin'

featured:
  - 2010-07-06-5D_7750_Artem_Sapegin
  - 2010-08-06_5D_9035_Artem_Sapegin
  - 2013-08-01_3402_Artem_Sapegin
  - 2012-08-20-5D_1332_Artem-Sapegin
