sourceFolder: source
sourceTypes:
  - md
  - txt
  - html
templatesFolder: templates
assetsFolder: public
publicFolder: public
photosFolder: photos

lang: en
url: http://morning.photos

artist: Artem Sapegin
