url: http://morning.photos
title: Artem Sapegin Photography
titleLong: "Artem Sapegin Photography: landscapes, travel, cityscapes, nature, dogs"
titleBlog: Artem Sapegin’s Photography Blog
author: Artem Sapegin
twitter: iamsapegin
fbapp: 155027288234245

menu:
  Blog: /blog
  Portfolio: /albums
  About: /about
  По-русски: http://birdwatcher.ru/

tagNames:
  photos: 'My Photos'
  photography: 'Photography'
  life: 'Life'
  dogs: 'Dogs'
  books: 'Books'
  masters: 'Masters'

readMore: Read more…
nextPage: Previously

share:
  facebook: Share
  twitter: Tweet

tags:
  title: '{total, plural, =1{One post} other{# posts}} tagged “{tag}”'

subscribe:
  id: e0d45226cc
  url: "https://photos.us8.list-manage.com/subscribe/post"
  endpoint: "https://photos.us8.list-manage.com/subscribe/post-json"
  info: A few times a year, no spam, unsubscribe at any time.
  emailLabel: Your email
  button: Subscribe!
  success: Almost done! Please confirm your subscription by opening a link in an email we have just sent you.
  error: Something went wrong, please try again later.
