url: http://birdwatcher.ru
title: Фотографии Артёма Сапегина
titleLong: "Фотографии Артёма Сапегина: пейзаж, городской пейзаж, путешествия, тревел, природа, собаки"
titleBlog: Блог о фотографии Артёма Сапегина
author: Артём Сапегин
twitter: sapegin
moot: birdwatcher

menu:
  Блог: /blog
  Фотографии: /albums
  Поездки: /travel
  Статьи: /learn
  Обо мне: /about
  In English: http://morning.photos/

tagNames:
  photos: 'Фотографии'
  photography: 'О фотографии'
  life: 'Жизнь'
  geeky: 'Гиковское'
  idiots: 'Идиоты'
  dogs: 'Собаки'
  books: 'Книги'
  horses: 'Лошади'
  masters: 'Мастера'
  humor: 'Юмор'

readMore: Читать дальше…
nextPage: Ранее

share:
  facebook: Поделиться
  twitter: Твитнуть

tags:
  title: '{total, plural, one{# пост} few{# поста} many{# постов} other{# поста}} с тегом «{tag}»'

subscribe:
  url: "http://birdwatcher.us8.list-manage.com/subscribe/post"
  endpoint: "http://birdwatcher.us8.list-manage.com/subscribe/post-json"
  title: 'Подпишитесь на мою рассылку о фотографии'
  info: 'Новые посты и фотографии, анонсы моих электронных книг и всякое такое. Не слишком часто, без спама.'
  emailLabel: Ваша почта
  button: Подписаться
  success: 'Спасибо! Вам осталось подтвердить подписку, кликнув ссылку в письме, которое вы сейчас получите.'
  error: 'Что-то пошло не так, попробуйте позже.'
